name: EBAC CI Mobile

on:
  push:
    branches: [ci]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install Dependencies
        run: |
          cd ebac-store-mobile-tests
          npm i

      - name: Run Tests (SauceLabs)
        run: |
          cd ebac-store-mobile-tests
          ENVIRONMENT=saucelabs npm t

      - name: Generate Allure Report
        run: |
          cd ebac-store-mobile-tests
          npm run allure:report

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ebac-store-mobile-tests/allure-report