name: EBAC CI Mobile

on:
  push:
    branches: [main, ci]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ebac-store-mobile-tests
        run: npm i

      - name: Run Tests
        run: npm t

      - name: Generate Allure Report
        working-directory: ebac-store-mobile-tests
        run: npm run allure:report

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ebac-store-mobile-tests/allure-report